adapter: mysql2            
host: 54.208.130.57                         # VM IP
port: 64431                          # VM Port 
database: demo_db             # Database Name
username: aggy48qy0uz7xrnn                # User Name
password: 'ay0ooox8slrm6uoa1arr7l4hzac6n3ge'  
