adapter: mysql2            
host: 54.208.130.57                         # VM IP
port: 53653                          # VM Port 
database: demo_db             # Database Name
username: aqfjgj73vsnmddoi                # User Name
password: 'acavceal34mvrqy3bry17bsain3gkw16'  
