adapter: mysql2            
host: 192.168.3.241                         # VM IP
port: 11622                          # VM Port 
database: demo_db             # Database Name
username: ad3swivaaof11fsw                 # User Name
password: 'ajsu40byqxqn67801pllyvm8lbt48gsk'                # Password
