adapter: mysql2            
host: 172.16.2.167                          # VM IP
port: 26280                          # VM Port 
database: demo_db             # Database Name
username: ayfybtyv1dj4n0w7                 # User Name
password: 'a82l3nqy2un12tszqhj76eegrkphaabh'                # Password
